services:
  relay:
    build:
      context: .
      target: final
    ports:
      - 7777:7777
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      - POSTGRES_DB=nostr
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env